name = "stars"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
mist = ">= 4.0.7 and < 5.0.0"
nakai = ">= 1.1.1 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
glanoid = ">= 1.0.1 and < 2.0.0"
dotenv_conf = ">= 0.2.0 and < 1.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
gsv = ">= 3.0.2 and < 4.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
argus = ">= 1.0.2 and < 2.0.0"
datastar_wisp = ">= 1.0.1 and < 2.0.0"
datastar = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
gwt = { path = "./gwt" }
gleam_otp = ">= 0.16.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
